import { test, expect } from '@playwright/test';



test('test', async ({ page }) => {
  await page.goto('https://topgeschenken.nl/');
  await page.getByRole('button', { name: 'Alles accepteren' }).click();
  await page.getByRole('link', { name: 'Chocolade Chocolade' }).click();
  await page.goto('https://topgeschenken.nl/chocolade');
  await page.getByRole('link', { name: /Tony's Chocolonely/ }).nth(1).click();
  await page.getByRole('button', { name: 'Voeg toe aan winkelwagen' }).click();
  await page.getByRole('button', { name: 'Doorgaan zonder kaartje' }).click();
  await page.getByRole('banner').filter({ hasText: 'Maak je bestelling extra' }).getByRole('link').click();
  await page.locator('#cart_order_deliveryAddressType').selectOption('1');
  await page.locator('#cart_order_deliveryAddressAttn').selectOption('1');
  await page.locator('#cart_order_deliveryAddressAttn').click();
  await page.locator('#cart_order_deliveryAddressAttn').fill('Eslem');
  await page.locator('#cart_order_deliveryAddressPostcode').click();
  await page.locator('#cart_order_deliveryAddressPostcode').fill('1010AA');
  await page.locator('#cart_order_deliveryAddressNumber').click();
  await page.locator('#cart_order_deliveryAddressNumber').fill('101');
  await page.locator('#cart_order_deliveryAddressStreet').click();
  await page.locator('#cart_order_deliveryAddressStreet').fill('koningStraat');
  await page.locator('#cart_order_deliveryAddressCity').dblclick();
  await page.locator('#cart_order_deliveryAddressCity').fill('Amsterdam');
  await page.getByRole('button', { name: 'Volgende stap' }).click();
  await page.locator('#cart_order_deliveryAddressPostcode').click();
  await page.locator('#cart_order_deliveryAddressPostcode').fill('1025KL');
  await page.locator('#cart_order_deliveryAddressNumber').click();
  await page.locator('#cart_order_deliveryAddressNumber').click();
  await page.getByLabel('april 10,').click();
  await page.locator('#cart_order_deliveryAddressStreet').click();
  await page.locator('#cart_order_deliveryAddressStreet').fill('Benedenlangs');
  await page.locator('#cart_order_deliveryAddressStreet').press('Tab');
  await page.locator('#cart_order_deliveryAddressCity').fill('Amsterdam');
  await page.locator('#cart_order_deliveryAddressPhoneNumber').click();
  await page.getByRole('cell', { name: '1025KD' }).click();
  await page.locator('#cart_order_deliveryAddressPhoneNumber').click();
  await page.locator('#cart_order_deliveryAddressPhoneNumber').fill('0642705555');
  await page.getByRole('button', { name: 'Volgende stap' }).click();
  await page.getByRole('radio', { name: 'Nee (doorgaan als gast)' }).check();
  await page.locator('#cart_customer_email').click();
  await page.locator('#cart_customer_email').fill('tester@1secmail.com');
  await page.getByText('Dhr.').click();
  await page.locator('#cart_customer_firstname').click();
  await page.locator('#cart_customer_firstname').fill('Enwer');
  await page.locator('#cart_customer_firstname').press('Tab');
  await page.locator('#cart_customer_lastname').fill('Memet');
  await page.locator('#cart_customer_default_invoice_address_postcode').click();
  await page.locator('#cart_customer_default_invoice_address_postcode').fill('1025KL');
  await page.locator('#cart_customer_default_invoice_address_postcode').press('Tab');
  await page.locator('#cart_customer_default_invoice_address_number').fill('100');
  await page.locator('#cart_customer_default_invoice_address_street').dblclick();
  await page.locator('#cart_customer_phonenumber').click();
  await page.locator('#cart_customer_phonenumber').fill('0604208888');
  await page.getByRole('checkbox', { name: 'Ik accepteer de algemene' }).check();
  await page.getByRole('checkbox', { name: 'Ik ontvang graag nieuws-en' }).uncheck();
  await page.getByRole('radio', { name: 'iDEAL' }).check();
  await page.getByRole('button', { name: 'Bestelling betalen' }).click();
  await page.getByTestId('payment-action-title').click();
  await page.getByTestId('payment-qr-title').click();
  await page.getByTestId('cancel-transaction-button').click();
  await page.getByTestId('cancel-transaction-confirm-dialog-confirm').click();
});